version: '3.2'

services:
  devenv:
    image: ronakvjain/devenv
    network_mode: 'service:dind'
    volumes:
      - home:/home/docker
      - ~/.ssh:/home/docker/.ssh:ro
      - ~/.gitconfig:/home/docker/.gitconfig:ro
      - ./host:/host
      # If you want to edit files on your host
      # change this to ./code:/storage, it will be
      # slower though as bind mounts suck.
      - ~/development/:/storage
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375

  dind:
    image: docker:stable-dind
    restart: always
    volumes:
      # If you want to edit files on your host
      # change this to ./code:/storage, it will be
      # slower though as bind mounts suck.
      - ~/development/:/storage
      - docker:/var/lib/docker
    privileged: true
    # May need to change this depending on the output
    # of docker info | grep -i "storage driver"
    command: --storage-driver=overlay
    ports:
      # Apps
      - 5000:5000
      - 9000:9000
      - 9001:9001
      - 9002:9002
      - 9003:9003

volumes:
  code:
  docker:
  home:
